batch_size: 24
batch_size_eval: 128
block: 2
checkpoint_start: null
ckpt_path: checkpoints/university/convnext_base.fb_in22k_ft_in1k_384/02/08_23:41:14/weights_e1_0.9356.pth
clip_grad: 100.0
cudnn_benchmark: true
cudnn_deterministic: false
custom_sampling: true
data_folder: ../../dataset/
dataset: U1652-D2S
dataset_name: University-Release
decay_exclue_bias: false
device: cuda
epochs: 1
eval_every_n_epoch: 1
eval_gallery_n: -1
gallery_folder_test: ../../dataset//University-Release/test/gallery_satellite
gallery_folder_train: ../../dataset//University-Release/train/drone
gpu_ids: '1'
grad_checkpointing: false
handcraft_model: true
img_size: 384
label_smoothing: 0.1
lr: 0.001
lr_blockweights: 2
lr_decouple: null
lr_end: 0.0001
lr_mlp: null
mixed_precision: true
model: convnext_base.fb_in22k_ft_in1k_384
model_path: ./checkpoints/university
nclasses: 701
normalize_features: true
num_workers: 4
only_test: false
prob_flip: 0.5
query_folder_test: ../../dataset//University-Release/test/query_drone
query_folder_train: ../../dataset//University-Release/train/satellite
record: true
resnet: false
scheduler: cosine
seed: 1
triplet_loss: 0.3
verbose: true
views: 2
warmup_epochs: 0.1
weight_cls: 0.1
weight_infonce: 1.0
weight_tri: 0.0
zero_shot: false
batch_size: 24
batch_size_eval: 128
block: 2
checkpoint_start: null
ckpt_path: checkpoints/university/convnext_base.fb_in22k_ft_in1k_384/02/08_23:41:14/weights_e1_0.9356.pth
clip_grad: 100.0
cudnn_benchmark: true
cudnn_deterministic: false
custom_sampling: true
data_folder: ../../dataset/
dataset: U1652-D2S
dataset_name: University-Release
decay_exclue_bias: false
device: cuda
epochs: 1
eval_every_n_epoch: 1
eval_gallery_n: -1
gallery_folder_test: ../../dataset//University-Release/test/gallery_satellite
gallery_folder_train: ../../dataset//University-Release/train/drone
gpu_ids: '1'
grad_checkpointing: false
handcraft_model: true
img_size: 384
label_smoothing: 0.1
lr: 0.001
lr_blockweights: 2
lr_decouple: null
lr_end: 0.0001
lr_mlp: null
mixed_precision: true
model: convnext_base.fb_in22k_ft_in1k_384
model_path: ./checkpoints/university
nclasses: 701
normalize_features: true
num_workers: 4
only_test: false
prob_flip: 0.5
query_folder_test: ../../dataset//University-Release/test/query_drone
query_folder_train: ../../dataset//University-Release/train/satellite
record: true
resnet: false
scheduler: cosine
seed: 1
triplet_loss: 0.3
verbose: true
views: 2
warmup_epochs: 0.1
weight_cls: 0.1
weight_infonce: 1.0
weight_tri: 0.0
zero_shot: false
batch_size: 24
batch_size_eval: 128
block: 2
checkpoint_start: null
ckpt_path: checkpoints/university/convnext_base.fb_in22k_ft_in1k_384/02/08_23:41:14/weights_e1_0.9356.pth
clip_grad: 100.0
cudnn_benchmark: true
cudnn_deterministic: false
custom_sampling: true
data_folder: ../../dataset/
dataset: U1652-D2S
dataset_name: University-Release
decay_exclue_bias: false
device: cuda
epochs: 1
eval_every_n_epoch: 1
eval_gallery_n: -1
gallery_folder_test: ../../dataset//University-Release/test/gallery_satellite
gallery_folder_train: ../../dataset//University-Release/train/drone
gpu_ids: '1'
grad_checkpointing: false
handcraft_model: true
img_size: 384
label_smoothing: 0.1
lr: 0.001
lr_blockweights: 2
lr_decouple: null
lr_end: 0.0001
lr_mlp: null
mixed_precision: true
model: convnext_base.fb_in22k_ft_in1k_384
model_path: ./checkpoints/university
nclasses: 701
normalize_features: true
num_workers: 4
only_test: false
prob_flip: 0.5
query_folder_test: ../../dataset//University-Release/test/query_drone
query_folder_train: ../../dataset//University-Release/train/satellite
record: true
resnet: false
scheduler: cosine
seed: 1
triplet_loss: 0.3
verbose: true
views: 2
warmup_epochs: 0.1
weight_cls: 0.1
weight_infonce: 1.0
weight_tri: 0.0
zero_shot: false
batch_size: 24
batch_size_eval: 128
block: 2
checkpoint_start: null
ckpt_path: checkpoints/university/convnext_base.fb_in22k_ft_in1k_384/02/08_23:41:14/weights_e1_0.9356.pth
clip_grad: 100.0
cudnn_benchmark: true
cudnn_deterministic: false
custom_sampling: true
data_folder: ../../dataset/
dataset: U1652-D2S
dataset_name: University-Release
decay_exclue_bias: false
device: cuda
epochs: 1
eval_every_n_epoch: 1
eval_gallery_n: -1
gallery_folder_test: ../../dataset//University-Release/test/gallery_satellite
gallery_folder_train: ../../dataset//University-Release/train/drone
gpu_ids: '1'
grad_checkpointing: false
handcraft_model: true
img_size: 384
label_smoothing: 0.1
lr: 0.001
lr_blockweights: 2
lr_decouple: null
lr_end: 0.0001
lr_mlp: null
mixed_precision: true
model: convnext_base.fb_in22k_ft_in1k_384
model_path: ./checkpoints/university
nclasses: 701
normalize_features: true
num_workers: 4
only_test: false
prob_flip: 0.5
query_folder_test: ../../dataset//University-Release/test/query_drone
query_folder_train: ../../dataset//University-Release/train/satellite
record: true
resnet: false
scheduler: cosine
seed: 1
triplet_loss: 0.3
verbose: true
views: 2
warmup_epochs: 0.1
weight_cls: 0.1
weight_infonce: 1.0
weight_tri: 0.0
zero_shot: false
batch_size: 24
batch_size_eval: 128
block: 2
checkpoint_start: null
ckpt_path: checkpoints/university/convnext_base.fb_in22k_ft_in1k_384/02/08_23:41:14/weights_e1_0.9356.pth
clip_grad: 100.0
cudnn_benchmark: true
cudnn_deterministic: false
custom_sampling: true
data_folder: ../../dataset/
dataset: U1652-D2S
dataset_name: University-Release
decay_exclue_bias: false
device: cuda
epochs: 1
eval_every_n_epoch: 1
eval_gallery_n: -1
gallery_folder_test: ../../dataset//University-Release/test/gallery_satellite
gallery_folder_train: ../../dataset//University-Release/train/drone
gpu_ids: '1'
grad_checkpointing: false
handcraft_model: true
img_size: 384
label_smoothing: 0.1
lr: 0.001
lr_blockweights: 2
lr_decouple: null
lr_end: 0.0001
lr_mlp: null
mixed_precision: true
model: convnext_base.fb_in22k_ft_in1k_384
model_path: ./checkpoints/university
nclasses: 701
normalize_features: true
num_workers: 4
only_test: false
prob_flip: 0.5
query_folder_test: ../../dataset//University-Release/test/query_drone
query_folder_train: ../../dataset//University-Release/train/satellite
record: true
resnet: false
scheduler: cosine
seed: 1
triplet_loss: 0.3
verbose: true
views: 2
warmup_epochs: 0.1
weight_cls: 0.1
weight_infonce: 1.0
weight_tri: 0.0
zero_shot: false
batch_size: 24
batch_size_eval: 128
block: 2
checkpoint_start: null
ckpt_path: checkpoints/university/convnext_base.fb_in22k_ft_in1k_384/02/08_23:41:14/weights_e1_0.9356.pth
clip_grad: 100.0
cudnn_benchmark: true
cudnn_deterministic: false
custom_sampling: true
data_folder: ../../dataset/
dataset: U1652-D2S
dataset_name: University-Release
decay_exclue_bias: false
device: cuda
epochs: 1
eval_every_n_epoch: 1
eval_gallery_n: -1
gallery_folder_test: ../../dataset//University-Release/test/gallery_satellite
gallery_folder_train: ../../dataset//University-Release/train/drone
gpu_ids: '1'
grad_checkpointing: false
handcraft_model: true
img_size: 384
label_smoothing: 0.1
lr: 0.001
lr_blockweights: 2
lr_decouple: null
lr_end: 0.0001
lr_mlp: null
mixed_precision: true
model: convnext_base.fb_in22k_ft_in1k_384
model_path: ./checkpoints/university
nclasses: 701
normalize_features: true
num_workers: 4
only_test: false
prob_flip: 0.5
query_folder_test: ../../dataset//University-Release/test/query_drone
query_folder_train: ../../dataset//University-Release/train/satellite
record: true
resnet: false
scheduler: cosine
seed: 1
triplet_loss: 0.3
verbose: true
views: 2
warmup_epochs: 0.1
weight_cls: 0.1
weight_infonce: 1.0
weight_tri: 0.0
zero_shot: false
